### ISSUE TITLE
cannot get it run on windows

### ISSUE THREAD

**Issue by Joylei** [lutsen/lagan#1]
php: 7.0
os: win10

get 500 error, unless change these lines of `public/index.php`
```php
// Make sure to add the missing details to the config.php file.
require __DIR__.'/../config.php'; // Note: change this path if your Lagan project is in a subdirectory

// Include the configuration for RedBean and autoloaders.
require __DIR__.'/../setup.php'; // Note: change this path if your Lagan project is in a subdirectory
```

**Comment by lutsen** [comment]
Thanks for your comment. That's strange, since your fix points to the same file as the original code. Unfortunately I don't have a Windows setup, so I can't test it myself. I'll try to look in to it some more later this week.

**Comment by lutsen** [comment]
Hi @Joylei, I updated the `public/index.php` file to fix your problem.
