### ISSUE TITLE
Position Property - Failed CSRF check!

### ISSUE THREAD

**Issue by jonasgeiler** [lutsen/lagan#3]
When I try to move an item, I get a "Failed CSRF check!". 
I fixed it by adding this to the javascript block:

```javascript
var newForm =
// ... 
.append( $('<input>', {
	'type': 'hidden',
	'name': '{{ csrf.keys.name }}',
	'value': '{{ csrf.name }}'
})).append( $('<input>', {
	'type': 'hidden',
	'name': '{{ csrf.keys.value }}',
	'value': '{{ csrf.value }}'
}));
```

I guess you added the CSRF protection to the delete button, but then forgot to do it for the position property too.
Good work with Lagan! It's like KeystoneJS for PHP!

~ Skayo

**Comment by jonasgeiler** [comment]
Btw if you read this:
I made a little theme for the admin panel!
-> https://github.com/Skayo/Lagan-Bulma-Theme

**Comment by lutsen** [comment]
Thanx for the fix, and great to hear you like Lagan. I'll mention your theme in the readme file. Love to hear about any of your future Lagan adventures!
